; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; 串口监视器波特率
monitor_speed = 115200

; 引入官方的 ESP32 摄像头库
lib_deps = 
    espressif/esp32-camera

; 编译参数配置 (极其重要)
build_flags =
    -DBOARD_HAS_PSRAM             ; 告诉编译器板子上有 PSRAM
    -DARDUINO_USB_MODE=1          ; 如果你通过 S3 的原生 USB 接口下载，通常需要这两个配置
    -DARDUINO_USB_CDC_ON_BOOT=0

; 配置 PSRAM 的类型
; 大多数 S3-CAM 使用的是 8MB 的 Octal SPI PSRAM，如果是 2MB 的 Quad SPI，请改为 qio_qspi
board_build.arduino.memory_type = qio_opi

monitor_filters = esp32_exception_decoder