; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM5
; 下面这行是重点，自动下载 LD2410 雷达解析库
lib_deps = 
    ncmreynolds/ld2410 @ ^0.1.3
    fastled/FastLED @ ^3.6.0
    esphome/ESP32-audioI2S @ ^2.0.7